repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-xml
      - id: check-xml
        types: [file] # without that key check doesn't work
        files: \.(project|cproject|mcproject)$
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - --autofix
          - --no-ensure-ascii
          - --no-sort-keys
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --config-data
          - >
            {
              extends: default,
              rules: {
                document-start: {
                  present: false
                },
                line-length: {
                     max: 160
                }
              }
            }

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: insert-license
        files: ''
        types_or: [c, header]
        args:
          - --comment-style=//
      - id: insert-license
        files: \.(asm|s\d?)$
        types_or: [text]
        args:
          - --comment-style=#

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.5
    hooks:
      - id: clang-format
        args:
          - --style=google
  - repo: local
    hooks:
      - id: dont-use-uppercase
        name: check no uppercase in filenames
        entry: <entry command is not used>
        language: fail
        files: .*[A-ZА-Я]+.*
        exclude: ^.*README\.md$|^LICENSE\.txt$|^Pipfile$
      - id: dont-use-underscores
        name: check no underscores in filenames
        entry: <entry command is not used>
        language: fail
        files: .*_.*
  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
      - id: cppcheck
        args:
          - --enable=warning
          - --inline-suppr
          - --language=c
          - --force
  - repo: https://review.elvees.com/pre-commit-hooks
    rev: 53a24a4dec9736b5e4a625e75c3172299357cc22
    hooks:
      - id: check-copyright
      - id: check-copyright
        types_or: [] # without that key check doesn't work
        files: ^.*\.mdb$
      - id: check-copyright
        types_or: [] # without that key check doesn't work
        files: \.(asm|s\d?)$
